

services:
  db:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: team02          # 원하는 DB 사용자명
      POSTGRES_PASSWORD: java  # 원하는 비밀번호
      POSTGRES_DB: team02db              # 생성할 DB 이름
    volumes:
      - pgdata:/var/lib/postgresql # 18버전 이상 사용 시 /data 삭제, 알아서 생성
    networks:
      - app-network

  backend:
    restart: always #서버재부팅, 컨테이너 크래시, 예외 종료 (자동 재기동)
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "8081"           # 외부 노출 안됨, 내부 통신만
    networks:
      - app-network
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/team02db #컨테이너끼리 포트 공개없이 통신가능
      SPRING_DATASOURCE_USERNAME: team02
      SPRING_DATASOURCE_PASSWORD: java


    volumes:
      - uploads:/team01/uploads/
      - images:/team01/images/


  nginx:
    restart: always  #EC2 재부팅 시 자동 복구
    image: nginx:alpine
    container_name: nginx
    ports: # 외부에서 접속하는 포트
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro   # 인증서 디렉토리 읽기전용(:ro) 마운트 ,
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:
  uploads:
  images:

networks:
  app-network:
