

services:
  db:
    image: postgres:18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: team02          # 원하는 DB 사용자명
      POSTGRES_PASSWORD: java  # 원하는 비밀번호
      POSTGRES_DB: team02db              # 생성할 DB 이름
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
    networks:
      - app-network
    ports:
      - "5432:5432"                  # 외부 접속이 필요하면 주석 해제
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "8080"           # 외부 노출 안됨, 내부 통신만
    networks:
      - app-network
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/team02db
      SPRING_DATASOURCE_USERNAME: team02
      SPRING_DATASOURCE_PASSWORD: java


    volumes:
      - uploads:/opt/team01/uploads/
      - noimages:/opt/team01/images/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"          # ⭐ 외부에서 접속하는 유일한 포트
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  pgdata:
  uploads:
  noimages:

networks:
  app-network:
